# Generated by Django 2.0.2 on 2018-03-15 20:02

from django.db import migrations, models
import landing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to='', validators=[landing.validators.validate_file_extension]),
        ),
    ]
